### ISSUE TITLE
Support caching

### ISSUE THREAD

**Issue by rikhuijzer** [rikhuijzer/PlutoStaticHTML.jl#26]
- [x] Register SHA of input and Julia version in output HTML. Output HTML is stored somewhere, so can be used as a place to store the cache (#27)
- [x] Encapsulate the PlutoStaticHTML inside a START and END so that the previous output can be extracted again from output (#28)
- [x] Only evaluate notebooks if SHA doesn’t match (only holds for deterministic scripts) (#28)
- [ ] Allow the cache to be based on a Git repository and not some other caching mechanism. The cache Action would need one action run per notebook and is deleted after 30 or so days. This can just be the output location of the HTML. Let users specify what dir to find the output HTML.

This would solve the problems of TuringTutorials.

As a side note: this wouldn’t solve another issue in this repo about caching only a part of the notebook.
